---
name: Test Docker image
on:
  - pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Debian stable
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.debian
          build-args: |
            WINE_FLAVOUR=stable
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max

      - name: Build Debian devel
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.debian
          build-args: |
            WINE_FLAVOUR=devel
          cache-from: type=local,src=/tmp/buildx-cache

      - name: Build Debian staging
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.debian
          build-args: |
            WINE_FLAVOUR=staging
          cache-from: type=local,src=/tmp/buildx-cache

      - name: Build Alpine stable
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.alpine
          build-args: |
            WINE_FLAVOUR=
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max

      - name: Build Alpine devel
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.alpine
          build-args: |
            WINE_FLAVOUR=-dev
          cache-from: type=local,src=/tmp/buildx-cache
  
  